// Test helpers for the streaming encode/decode engine and the
// streaming worker jobs. Not a test file . leading underscore so the
// manifest's `tests` glob would ignore it if we ever globbed; the
// manifest is explicit anyway.
//
// These helpers are pure test glue: they let tests with in-memory
// byte payloads or string covers drive the streaming surfaces
// without each call site cloning the same wiring boilerplate.

import { readFileSync } from './shims/node-fs.js';
import { gunzipSync } from './shims/node-zlib.js';
import { encode } from '../../js/src/encode.js';
import { decode } from '../../js/src/decode.js';
import { parseTwlistLines } from '../../js/src/builder/sources.js';
import { wrapDictionaryFromSAB } from '../../js/src/dictionary.js';
import { wrapModelTableFromSAB } from '../../js/src/modeltable.js';
import { unpack as sabUnpack } from '../../js/src/sab.js';
import {
  findCardByName, getDictPath, getModelPath, getCorpusPath,
} from '../../js/src/byos.js';
// Synchronous ESM import, the cards registry is the single runtime
// source of truth for fixture filename resolution. fixtures/cards.data.js
// is auto-generated by tools/build-all-fixtures.js (do not edit by
// hand). See that file's header for regeneration instructions.
import cardsRegistry from '../../fixtures/cards.data.js';

// Resolve a fixture URL by card nickname (the raw byos.name, e.g.
// "random" or "aesop"). kind is 'dict' (default) or 'model'. The
// rev-suffix and any future filename-shape changes flow through
// getBYOSID inside getDictPath / getModelPath.
export function fixtureURL(cardName, baseURL, kind = 'dict') {
  const card = findCardByName(cardName, cardsRegistry);
  if (!card) throw new Error(`fixtureURL: no card named "${cardName}"`);
  const rel = kind === 'model'
    ? getModelPath(card, cardsRegistry)
    : getDictPath(card, cardsRegistry);
  return new URL(`../../${rel}`, baseURL);
}

// Resolve the source corpus URL for a card. Cards without a build
// corpus (the synthetic ones, e.g. random / mit) throw.
export function corpusFixtureURL(cardName, baseURL) {
  const card = findCardByName(cardName, cardsRegistry);
  if (!card) throw new Error(`corpusFixtureURL: no card named "${cardName}"`);
  const rel = getCorpusPath(card);
  if (!rel) throw new Error(`corpusFixtureURL: card "${cardName}" has no corpus`);
  return new URL(`../../${rel}`, baseURL);
}

// Read a .txt.gz corpus fixture and return its UTF-8 text. Node:
// readFileSync returns a Buffer that needs gunzip + utf-8 decode.
// Browser: the node-fs shim already gunzipped + decoded at preload
// time and readFileSync returns a string.
export function loadCorpusText(url) {
  const data = readFileSync(url);
  if (typeof data === 'string') return data;
  return gunzipSync(data).toString('utf8');
}

// Read a JSON file at <url>, gunzipping when the path ends in .gz.
// Used by tests that load chip dictionaries / model tables out of
// fixtures/ where everything is gzipped on disk. Works in both node
// (real fs returns Buffer) and test-suite.html browser mode (the node-fs
// shim decompresses .gz at preload time and readFileSync returns
// already-decompressed text).
export function readJsonMaybeGz(url) {
  const data = readFileSync(url);
  if (typeof data === 'string') return JSON.parse(data);
  const path = url instanceof URL ? url.pathname : url;
  const text = String(path).endsWith('.gz')
    ? gunzipSync(data).toString('utf8')
    : data.toString('utf8');
  return JSON.parse(text);
}

// Read a TSV twlist fixture at <url>, gunzipping when the path ends in
// .gz, and return the parsed [{type, word}, ...] array. Same node /
// browser-shim duality as readJsonMaybeGz. # comment lines are skipped
// by parseTwlistLines so the # title: / # attribution: header lines in
// each fixture pass through transparently.
export function readTwlistMaybeGz(url) {
  const data = readFileSync(url);
  if (typeof data === 'string') return parseTwlistLines(data);
  const path = url instanceof URL ? url.pathname : url;
  const text = String(path).endsWith('.gz')
    ? gunzipSync(data).toString('utf8')
    : data.toString('utf8');
  return parseTwlistLines(text);
}

// Read a fixture URL as raw bytes, gunzipping when the path ends in
// .gz. Mirrors readJsonMaybeGz / readTwlistMaybeGz but skips text
// decode: used by SAB fixtures whose payload is a binary blob that
// must be copied byte-for-byte into a SharedArrayBuffer.
//
// Node returns Buffer (compressed for .gz); the browser shim returns
// a Uint8Array (decompressed by the shim's preload if .gz). The
// branch is on `Buffer.isBuffer(data)` so the helper handles both.
export function readBytesMaybeGz(url) {
  const data = readFileSync(url);
  if (typeof data === 'string') {
    // Browser shim served the file as text (non-SAB path). Encode
    // back to bytes; callers reaching here for a real binary fixture
    // would have been misclassified by the shim.
    return new TextEncoder().encode(data);
  }
  const path = url instanceof URL ? url.pathname : url;
  if (typeof Buffer !== 'undefined' && Buffer.isBuffer(data)) {
    return String(path).endsWith('.gz') ? gunzipSync(data) : data;
  }
  // Browser-shim Uint8Array path: already decompressed by the shim.
  return data;
}

// Wrap a fetched SAB-fixture byte buffer in a SharedArrayBuffer.
function bytesToSAB(bytes) {
  const view = new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const sab = new SharedArrayBuffer(view.byteLength);
  new Uint8Array(sab).set(view);
  return sab;
}

// One-call loaders for the *.dict.sab.gz / *.model.json[.gz] fixture
// shapes. Each test that wants a runtime dict or model table used to
// repeat readJsonMaybeGz(...) followed by loadDictionary(...) /
// loadModelTable(...); these collapse the pair to a single call so
// adding or moving a fixture only needs one edit per test.
//
// loadDictFixture now reads the canonical SAB fixture and wraps it
// without going through JSON.parse, the on-disk dict form is the
// already-compiled SAB binary post sab-fixtures arc.
export function loadDictFixture(url) {
  return wrapDictionaryFromSAB(bytesToSAB(readBytesMaybeGz(url)));
}
// Variant that returns the dict JSON shape ({version, types, words})
// rather than the runtime wrapper. Used by analysis tests that walk
// dict.types / dict.words directly (huffman-tiebreaker, etc.). Routes
// through sab.unpack('dict', sab) for the SAB → JSON inverse.
export function loadDictJsonFixture(url) {
  return sabUnpack(bytesToSAB(readBytesMaybeGz(url)), 'dict');
}
// loadModelTableFixture mirrors loadDictFixture: reads the canonical
// SAB model-table fixture and wraps it without JSON.parse.
export function loadModelTableFixture(url) {
  return wrapModelTableFromSAB(bytesToSAB(readBytesMaybeGz(url)));
}
// Variant returning the model-table JSON shape via sab.unpack('model').
// Used by modeltable-sab.test.js for cross-format invariants.
export function loadModelTableJsonFixture(url) {
  return sabUnpack(bytesToSAB(readBytesMaybeGz(url)), 'model');
}

export function bytesToStream(bytes) {
  return new ReadableStream({
    start(c) {
      if (bytes && bytes.length > 0) c.enqueue(bytes);
      c.close();
    },
  });
}

export function stringToStream(s) {
  return bytesToStream(new TextEncoder().encode(s));
}

// Build a WritableStream<Uint8Array> sink that captures every chunk
// in order. `result()` joins the chunks into a single Uint8Array.
export function captureBytesSink() {
  const chunks = [];
  const writable = new WritableStream({
    write(chunk) { chunks.push(chunk); },
  });
  return {
    writable,
    result() {
      let total = 0;
      for (const c of chunks) total += c.length;
      const out = new Uint8Array(total);
      let offset = 0;
      for (const c of chunks) { out.set(c, offset); offset += c.length; }
      return out;
    },
    resultAsString() {
      return new TextDecoder().decode(this.result());
    },
  };
}

// Drain a ReadableStream<Uint8Array> into a single Uint8Array.
export async function streamToBytes(stream) {
  const reader = stream.getReader();
  const chunks = [];
  let total = 0;
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    chunks.push(value);
    total += value.length;
  }
  const out = new Uint8Array(total);
  let offset = 0;
  for (const c of chunks) { out.set(c, offset); offset += c.length; }
  return out;
}

// Drain a ReadableStream<Uint8Array> into a UTF-8 string.
export async function streamToString(stream) {
  const dec = new TextDecoder();
  const reader = stream.getReader();
  let s = '';
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    s += dec.decode(value, { stream: true });
  }
  s += dec.decode();
  return s;
}

// Convenience: stream a byte payload through encode and return the
// cover text as a string.
export async function encodeToString(payload, dict, opts = {}) {
  const sink = captureBytesSink();
  await encode(bytesToStream(payload), sink.writable, dict, opts);
  return sink.resultAsString();
}

// Convenience: stream a cover-text string through decode and return
// the recovered bytes.
export async function decodeToBytes(coverText, dict, opts = {}) {
  const sink = captureBytesSink();
  await decode(stringToStream(coverText), sink.writable, dict, opts);
  return sink.result();
}
